services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt:rw
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - php
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt:rw
      - .:/var/www/html

  postgres:
    image: postgres:latest
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    volumes:
      - ./nginx_logs:/var/log/nginx

volumes:
  postgres_data:
  certs:
  certbot-etc:
  var-lib-letsencrypt:
  nginx_logs:
