services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/conf.d/adminer.conf:/etc/nginx/conf.d/adminer.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - php
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-etc:/etc/letsencrypt/config
      - ./var-lib-letsencrypt:/var/lib/letsencrypt

  postgres:
    image: postgres:latest
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
  certs:
  certbot-etc:
  var-lib-letsencrypt:
